### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [rugheid/Swift-MathEagle#9]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by rugheid** [comment]
There is a `swift-3` branch, you can use that one! :)

**Comment by lfarah** [comment]
Since Xcode 8 is out, I think it's time to merge it into master. What do you think?

I'll take a look at the `swift-3` branch 😉

**Comment by rugheid** [comment]
Yes, it might be a good idea to make the master branch use swift 3. I'm going to keep the swift 2 version for a while though, there might be people who haven't moved yet.

**Comment by lfarah** [comment]
I'm helping a lot of libraries of different sizes with this update.
What most of them are doing is to keep Swift 3 on master and then have a branch for Swift 2.2 and 2.3

**Comment by rugheid** [comment]
That's what I was thinking as well... 😀 It's all set now.
